name: fullproductpage
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  google_fonts: ^6.2.1   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/headerImage.png
    - assets/variationImage1.png
    - assets/variationImage2.png
    - assets/variationImage3.png
    - assets/reviewImage1.png
    - assets/mostPopularImage1.png
    - assets/mostPopularImage2.png
    - assets/mostPopularImage3.png
    - assets/mostPopularImage4.png
